trigger:
  none

pr:
  branches:
    include:
      - main

variables:
  - name: solution
    value: '**/*.sln'
  - name: buildConfiguration
    value: 'Release'

jobs:
- job: BuildAndPackage
  displayName: 'Restore, Build Library and WPF Project, and Package'
  pool:
    vmImage: 'windows-latest'
  steps:
    - checkout: self
    - task: NuGetToolInstaller@1
      displayName: 'Install NuGet'
    - task: NuGetCommand@2
      displayName: 'Restore NuGet packages'
      inputs:
        command: 'restore'
        restoreSolution: '$(solution)'
        verbosityRestore: 'Detailed'
        packagesDirectory: '$(Build.SourcesDirectory)\packages'
    - task: VSBuild@1
      displayName: 'Clean and Build Library'
      inputs:
        solution: 'PaintingLibrary/PaintingLibrary.csproj'
        configuration: '$(buildConfiguration)'
        msbuildArgs: '/t:Clean;Build'

    - task: VSBuild@1
      displayName: 'Build WPF Project'
      inputs:
        solution: 'PaintingDetailsManager/PaintingDetailsManager.csproj'
        configuration: '$(buildConfiguration)'

    - task: PowerShell@2
      displayName: 'Ensure Data/Working and Data/Images Folders Exist'
      inputs:
        targetType: 'inline'
        script: |
          echo "Creating necessary folders in Data directory..."
          if (-not (Test-Path -Path "$(Build.SourcesDirectory)\PaintingDetailsManager\Data\Working")) {
              New-Item -ItemType Directory -Path "$(Build.SourcesDirectory)\PaintingDetailsManager\Data\Working"
          }
          if (-not (Test-Path -Path "$(Build.SourcesDirectory)\PaintingDetailsManager\Data\Images")) {
              New-Item -ItemType Directory -Path "$(Build.SourcesDirectory)\PaintingDetailsManager\Data\Images"
          }

    - task: CopyFiles@2
      displayName: 'Copy Clean Database to Working Directory'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)\PaintingDetailsManager\Data\Clean'
        Contents: 'paintings.db'
        TargetFolder: '$(Build.SourcesDirectory)\PaintingDetailsManager\Data\Working'

    - task: PowerShell@2
      displayName: 'Create Zip File'
      inputs:
        targetType: 'inline'
        script: |
          echo "Zipping files..."
          $outputPath = '$(Build.ArtifactStagingDirectory)\PaintingDetailsManager'
          if (-not (Test-Path -Path $outputPath)) {
              New-Item -ItemType Directory -Path $outputPath
          }
          Add-Type -AssemblyName System.IO.Compression.FileSystem
          $zipPath = '$(Build.ArtifactStagingDirectory)\PaintingDetailsManager\PaintingDetailsManager.zip'
          $sourceDir = '$(Build.SourcesDirectory)\PaintingDetailsManager\bin\Release'
          [System.IO.Compression.ZipFile]::CreateFromDirectory($sourceDir, $zipPath)

    - task: CmdLine@2
      displayName: 'Check Zip File Contents'
      inputs:
        script: |
          echo "Checking contents of the zip file..."
          tar -tf "$(Build.ArtifactStagingDirectory)\PaintingDetailsManager\PaintingDetailsManager.zip"

    - task: PublishBuildArtifacts@1
      displayName: 'Publish WPF Artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)\PaintingDetailsManager\PaintingDetailsManager.zip'
        ArtifactName: 'PaintingDetailsManager'
        publishLocation: 'Container'
        ArtifactType: 'Container'

    - task: CmdLine@2
      displayName: 'Listing Artifact Staging Directory (Detailed) Contents'
      inputs:
        script: |
          echo "-----------Contents of the Artifact Staging Directory-----------"
          dir /s D:\a\1\a
          echo "-----------Contents of the PaintingDetailsManager folder inside the Artifact Staging Directory-----------"
          dir /s D:\a\1\a\PaintingDetailsManager

    - task: GitHubRelease@0
      inputs:
        gitHubConnection: 'github.com_zacharywatson1129'  # Define your GitHub connection in the DevOps project settings
        repositoryName: 'zacharywatson1129/Painting-Manager'
        target: 'main'
        tagSource: 'manual'  # You can also choose 'build' if you want it to auto-tag
        tag: 'v$(Build.BuildId)'
        title: 'Release $(Build.BuildId)'
        assets: '$(Build.ArtifactStagingDirectory)\PaintingDetailsManager\PaintingDetailsManager.zip'  # Point to your zip
